### ISSUE TITLE
Exception in on_message

### ISSUE THREAD

**Issue by theDebonair** [QuartzWarrior/Tip.cc-Autocollect#1]
![image](https://user-images.githubusercontent.com/51323434/176002951-ab305250-683c-4b2f-a89d-7922cbeb54d0.png)

**Comment by QuartzWarrior** [comment]
Yes, we have an update coming very soon.

**Comment by theDebonair** [comment]
Awesome. I want to buy premium. Any promo code?

**Comment by QuartzWarrior** [comment]
Updated
