### ISSUE TITLE
How to deactivate self tip

### ISSUE THREAD

**Issue by mpol12** [QuartzWarrior/Tip.cc-Autocollect#10]
Hi!
The script works great with airdrops which come with a sign button.
What creates issues for me is that it's constantly posting "$tip <my account> all Polygon" and the server replies that I cannot "self-tip"

How can I deactivate this feature??

**Comment by QuartzWarrior** [comment]
Looks like I forgot to disable it if it's the main accounts ID. This feature is used to send crypto claimed from alts to your main account. I'll update it later today with a fix.

**Comment by mpol12** [comment]
Thank U!
