### ISSUE TITLE
Client.__init__() missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by mpol12** [QuartzWarrior/Tip.cc-Autocollect#11]
Hi!
I installed and run the script.
I had an issue with "self tipping" (fixed in the latest update!!!)  and I decided to try out another script.
For that reason I run "pip install discord". After that Tip.cc-Autocollect has been giving me the following error...

> Traceback (most recent call last):
>   File "D:\Tip.cc-AutoCollector\tipcc_autocollect.py", line 246, in <module>
>     client = Client()
>              ^^^^^^^^
> TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

I also tried uninstalling discord (pip install discord) but the error remained.

How do I fix this?

Thank you in advance!
Mike

**Comment by QuartzWarrior** [comment]
Hi! the easiest way is to open [tipcc_autocollect.py](https://github.com/QuartzWarrior/Tip.cc-Autocollect/blob/main/tipcc_autocollect.py) and change `discord` in lines [16](https://github.com/QuartzWarrior/Tip.cc-Autocollect/blob/main/tipcc_autocollect.py#L16) and [17](https://github.com/QuartzWarrior/Tip.cc-Autocollect/blob/main/tipcc_autocollect.py#L17) to `selfcord` then run the below command:

```bash
# Linux/macOS
python3 -m pip install git+https://github.com/dolfies/discord.py-self@renamed#egg=selfcord.py[voice]

# Windows
py -3 -m pip install git+https://github.com/dolfies/discord.py-self@renamed#egg=selfcord.py[voice]
```

This should fix the issue.

**Comment by mpol12** [comment]
Good morning!!
Thank you for the quick fix.
I appreciate your support.
