### ISSUE TITLE
Install Error: Cannot find command 'git'

### ISSUE THREAD

**Issue by denz8ty** [QuartzWarrior/Tip.cc-Autocollect#12]
this the error message:  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/dolfies/discord.py-self.git 'C:\Users\genericuser\AppData\Local\Temp\pip-req-build-2psyj3zv'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by QuartzWarrior** [comment]
https://www.geeksforgeeks.org/how-to-install-git-on-windows-command-line/
