### ISSUE TITLE
Skipping Airdrop channel

### ISSUE THREAD

**Issue by paragbml** [QuartzWarrior/Tip.cc-Autocollect#13]
it is skipping airdrop-begging channel, any fix?

**Comment by QuartzWarrior** [comment]
No, that shouldn't be an issue. Can you send your configuration minus the token?

**Comment by paragbml** [comment]
hey! it did work after configuring it a bit.. but now im banned due to consequent accepting airdrops lmao i did use the smart delay feature but i guess it needs some work on it.

**Comment by QuartzWarrior** [comment]
Mind sending me your config? Smart delay waits 1/4 of the time until the drop ends, so if it was a 10 second drop, it waits 2.5 seconds before claiming.

**Comment by paragbml** [comment]
{
    "TOKEN": "--",
    "CPM": 800,
    "FIRST": false,
    "id": --,
    "channel_id": --,
    "TARGET_AMOUNT": 0.5,
    "SMART_DELAY": true,
    "DELAY": 1,
    "BANNED_WORDS": [
        "bot",
        "ban"
    ],
    "WHITELIST": [
        617034883503620167
    ],
    "BLACKLIST": [],
    "CHANNEL_BLACKLIST": [],
    "IGNORE_USERS": [],
    "WHITELIST_ON": true,
    "BLACKLIST_ON": false,
    "CHANNEL_BLACKLIST_ON": false,
    "IGNORE_DROPS_UNDER": 1e-38,
    "IGNORE_TIME_UNDER": 0.0,
    "IGNORE_THRESHOLDS": [],
    "DISABLE_AIRDROP": false,
    "DISABLE_TRIVIADROP": false,
    "DISABLE_MATHDROP": false,
    "DISABLE_PHRASEDROP": false,
    "DISABLE_REDPACKET": false
}

**Comment by paragbml** [comment]
also, this error occurs alot, any fix? the error msg:
 ERROR    tipcc_autocollect Index error occurred during money splitting, skipping... (tipcc_autocollect.py:541)
Traceback (most recent call last):
  File "/home/-/Downloads/Tip.cc-Autocollect-main/tipcc_autocollect.py", line 534, in on_message
    embed.description.split("≈")[1]
IndexError: list index out of range

**Comment by QuartzWarrior** [comment]
Alright, I might have an idea of what the problem is, I'll check if it actually is though, not entirely sure.
