### ISSUE TITLE
How to use the config

### ISSUE THREAD

**Issue by SandoCoin** [QuartzWarrior/Tip.cc-Autocollect#14]
You should add what exactly does the configs do and how to use them

**Comment by QuartzWarrior** [comment]
Alright, next update will include this

**Comment by QuartzWarrior** [comment]
@SandoCoin 
When you first run the script, it will lead you through steps on setting up the config, adding more documentation now though.

**Comment by SandoCoin** [comment]
btw what is this "Index error occurred during money splitting,". It happens when the coin has no value
