### ISSUE TITLE
Bug when coin has no value and ignore threshold not working

### ISSUE THREAD

**Issue by SandoCoin** [QuartzWarrior/Tip.cc-Autocollect#15]
It shows "Index error occurred during money splitting, skipping" when coin has no value

**Comment by QuartzWarrior** [comment]
Is there a way you can give me some of this non value coin so that I can test with it?

**Comment by SandoCoin** [comment]
Any coin that doesnt show up a value in tip.cc

**Comment by QuartzWarrior** [comment]
Yeah, the problem is I haven't been running the script on any servers, I essentially just maintain the script 💀

**Comment by SandoCoin** [comment]
you could try on yourself if possible

**Comment by QuartzWarrior** [comment]
Yeah, I do, but I mean, I can't obtain these cryptos with no value if I don't automate, so if you can, can you join discord.gg/ligma and send me one of these non value coins?
