### ISSUE TITLE
Can't start the tip.cc file in python (Termux)

### ISSUE THREAD

**Issue by 123mukund** [QuartzWarrior/Tip.cc-Autocollect#18]
![Screenshot_2024-10-04-13-25-11-63_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/d16ef67e-05f3-4731-b46d-3463cea1e973)
Please resolve that for me date (Friday,4 oct 2024)

**Comment by QuartzWarrior** [comment]
Please run this command: 
`python -m pip install --force-reinstall git+https://github.com/dolfies/discord.py-self.git`

**Comment by 123mukund** [comment]
Now I am getting this error thanks first one have been solved

**Comment by 123mukund** [comment]
Can you solve it please

**Comment by QuartzWarrior** [comment]
what do you mean, it is solved. I just sent you the solution..

**Comment by 123mukund** [comment]
![Screenshot_2024-10-05-06-42-30-31_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/ab0da752-b3a4-4de5-9c5e-21b586e08441)
![Screenshot_2024-10-05-06-45-38-77_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/95cdef0d-4c57-4c4b-94e2-2625c41d9127)








I don't know what's happening here

**Comment by QuartzWarrior** [comment]
your config.json might be messed up. delete it and re-run the script.

**Comment by 123mukund** [comment]
WOW! ITS WORKING
