### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kevincrafturu2** [QuartzWarrior/Tip.cc-Autocollect#2]
Hi, i use the free version and i use replit (an free host) to use this, but i cant because it appears and error and it says  Replit: Updating package configuration

--> python3 -m poetry init --no-interaction --name repl_nix_Tipcc-Autocollect
/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/bin/python3: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed
exit status 1

**Comment by kevincrafturu2** [comment]
if any with replit have this error it will be good to see if its replit or its the project or and best alternative to use this

**Comment by QuartzWarrior** [comment]
Disable poetry/search for packages, and do python -m pip install -U -r requirements.txt

**Comment by kevincrafturu2** [comment]
How can i disable it? Or how can i instal requirments.txt there?

**Comment by Clockodilee** [comment]
You can disable it by clicking the 3 dots, "show hidden files", then go to ".replit", scroll all the way down and set "guessImports" to False

**Comment by kevincrafturu2** [comment]
Oh thanks yo!

**Comment by kevincrafturu2** [comment]
![Captura de pantalla 2022-07-30 154756](https://user-images.githubusercontent.com/48927699/181937461-87a62bf0-e078-49b7-a05c-199750d5da18.jpg)
it appears this as you see its disabled

**Comment by QuartzWarrior** [comment]
You must run that command in the "shell" tab.

**Comment by kevincrafturu2** [comment]
It gives an error
>>> python -m pip install -U -r requirements.txt
  File "<stdin>", line 1
    python -m pip install -U -r requirements.txt
              ^
SyntaxError: invalid syntax
>>>

**Comment by QuartzWarrior** [comment]
> It gives an error
> >>> python -m pip install -U -r requirements.txt
>   File "<stdin>", line 1
>     python -m pip install -U -r requirements.txt
>               ^
> SyntaxError: invalid syntax
> >>> 

Are you running it in the "console" tab or the "shell" tab ?

**Comment by kevincraftuy2** [comment]
Hi im having problems in the other acc,  so im running that in shell ofc and it says ~/Tipcc-Autocollect$ python -m pip install -U -r requirements.txt
/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/bin/python: No module named pip
~/Tipcc-Autocollect$

**Comment by kevincraftuy2** [comment]
But if i use python and after python -m pip install -U -r requirements.txt it says  that of invalid syntax

**Comment by kevincraftuy2** [comment]
If you have the project in replit running pls send a link to fork it or idk

**Comment by QuartzWarrior** [comment]
Open the "replit.nix"

Replace everything with

```
{ pkgs }: {
  deps = [
    pkgs.python38Full
  ];
  env = {
    PYTHON_LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
      # Needed for pandas / numpy
      pkgs.stdenv.cc.cc.lib
      pkgs.zlib
      # Needed for pygame
      pkgs.glib
      # Needed for matplotlib
      pkgs.xorg.libX11
    ];
    PYTHONBIN = "${pkgs.python38Full}/bin/python3.8";
    LANG = "en_US.UTF-8";
  };
}
```

**Comment by kevincraftuy2** [comment]
~/Tipcc-Autocollect$ python -m pip install -U -r requirements.txt
/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/bin/python: No module named pip
Detected change in environment, reloading shell...
~/Tipcc-Autocollect$ 

 same

**Comment by kevincraftuy2** [comment]
Or if its for replit its there any free host like replit 24/7 but not heroku?

**Comment by QuartzWarrior** [comment]
Well you can use Oracle which works really well, but you need a credit card to verify. It is completely free though.

**Comment by QuartzWarrior** [comment]
Mind sending me the link to your repl ?

**Comment by kevincraftuy2** [comment]
sure

**Comment by kevincraftuy2** [comment]
https://replit.com/join/zypvrxozuc-kevincrafturu2f

**Comment by kevincraftuy2** [comment]
Yo i founded that  replit of you im using it thx

**Comment by QuartzWarrior** [comment]
Sure

**Comment by kevincrafturu2** [comment]
Ready, two more questions and i will close, How can i make an cooldoown to dont get caught because in 1cpm i got banned in an alt i have 2 more alts and how can i gain the crypto from an channel and tip from another channel

**Comment by QuartzWarrior** [comment]
Did I not add that feature yet ? I thought I did.

**Comment by QuartzWarrior** [comment]
We are still working on a multi token feature, but for now you can create multiple repls.

**Comment by QuartzWarrior** [comment]
When it asks:
> "What is the channel id where you want your alt to tip your main?
> (Remember, the tip.cc bot has to be in the server with this channel.)
> 
> If None, send 1.

> -> "
that is asking what channel you want your alts to tip to your main account.

**Comment by kevincrafturu2** [comment]
Alr, so its there an code that i can delete to only claim aidrops? Not phrase drop or redpackets just aidrops

**Comment by QuartzWarrior** [comment]
I can add that, sure. Thanks for the suggestion.

**Comment by kevincrafturu2** [comment]
Alr i was asking like delete some code rn but ido thanks for answering

**Comment by QuartzWarrior** [comment]
@kevincrafturu2 you can just change 
```elif "Phrase drop!" in embed.title:```
to 
```elif "Phrase drop!" in embed.title and False:```
