### ISSUE TITLE
intents error

### ISSUE THREAD

**Issue by homleshobo** [QuartzWarrior/Tip.cc-Autocollect#24]
How do I resolve this

  File "C:\Users\Home\Desktop\autocollect\tipcc_autocollect.py", line 518, in <module>
    client = Client(
        status=(
    ...<11 lines>...
        )
    )
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by QuartzWarrior** [comment]
```
python -m pip uninstall discord.py

python -m pip install --force-reinstall git+https://github.com/dolfies/discord.py-self.git
```
