### ISSUE TITLE
Invalid Token Issue

### ISSUE THREAD

**Issue by Backslid3** [QuartzWarrior/Tip.cc-Autocollect#6]
I am a NOOB with barely any knowledge but I managed to overcome almost every issue i encountered, from downloading the proper python version 3.11, because the newest one requires some sort of 'intent' on the code regarding the client which also related to ahttp module needed to be either downgraded or upgraded can't remember but the beta version didn't work with python 3.12 since apparently they didn't compile or added it to the new version only in beta mode. Finally I was able to run the script after uninstalling discord and also discord.py most recent version and installing and older one (version 1.7.3). Got past all of that but now i am stuck in the "Invalid token, restart the program" message, after I input the discord token, everything else is already set up. I am hoping it is an issue on my end, could you help me out please? I got the discord token from the dev tools "application" option bar and then filtered to "token". Got the string of numbers from there and copy and pasted into the program yet it still says invalid token, any ideas of what could be causing this?  I really appreciate your help, if i can run this i will absolutely share with you.

**Comment by QuartzWarrior** [comment]
Contact me on discord: `quartzwarrior`

**Comment by captkoksock** [comment]
> Contact me on discord: `quartzwarrior`

I sent you a friend request on discord, stonedwon. Looking for a hand setting this up if you have the time!
