### ISSUE TITLE
Not claiming

### ISSUE THREAD

**Issue by Trollserver** [QuartzWarrior/Tip.cc-Autocollect#9]
It just says waited 32 seconds before claiming for example but it never claims it and doesn't say the name of the coin and price like joined airdrop for 137 satoshi.

**Comment by QuartzWarrior** [comment]
Is there a chance the drop ended before it could be claimed? When the max amount of people enter the airdrop, it'll end automatically.

**Comment by QuartzWarrior** [comment]
Just added clean logging as well, so you can turn INFO mode to DEBUG on [line 62](https://github.com/QuartzWarrior/Tip.cc-Autocollect/blob/main/tipcc_autocollect.py#L62) and it'll give you quite a bit more information on what is happening, so you can provide me more information on this problem.

**Comment by Trollserver** [comment]
yes you are right, the airdrop ended
